name: Sync with upstream
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 5"
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Fetch file from upstream
        run: |
          rm spells/advertisinglite.sgmodule && curl -sSL https://github.com/blackmatrix7/ios_rule_script/raw/master/rewrite/Surge/AdvertisingLite/AdvertisingLite_Mock.sgmodule | sed -e "s/blackmatrix7/Kosette/g" -e "s/ios_rule_script/surfings/g" > spells/advertisinglite.sgmodule
      - name: Push to Repository
        run: |
          rm -rf .git
          git init
          git config --local user.name "kosette"
          git config --local user.email "35268640+Kosette@users.noreply.github.com"
          git add -A
          git commit -m "add files"
          git remote add geoip "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push -f geoip master
